[toolchain]


[features]
seeds = false
skip-lint = false

[programs.localnet]
bank_app = "9UqpozB7nRkDimT3SN88hD58tnVqzeBQtT9bBsNn1hc7"

[programs.devnet]
bank_app = "9UqpozB7nRkDimT3SN88hD58tnVqzeBQtT9bBsNn1hc7"


[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/duongnt/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
