[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
bank_app = "J7Kn4y5HtrjAwbK7mTwrko52mkPrVUgxw9R8M2HGJZDH"
staking-app = "81Rif9LTxch9oKZRSNH73epc3p5FkZUcd4Zq55gva7YR"
token_staking_app = "9bZdHwnp66yWMNCKET2Dxz1LfoVAvNHdPE5VdgHgh2JK"

[programs.localnet]
bank_app = "J7Kn4y5HtrjAwbK7mTwrko52mkPrVUgxw9R8M2HGJZDH"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
